import { Metadata } from "next";
export const metadata: Metadata = {
  title: {
    // To ignore the template title set in the parent page
    absolute: "Home",
    //for child routes : If they don't have the title defined
    default: "Child routes fall back",
    // For template iterals : %s will be replaced by the child title
    template: "%s - Next js tutorial",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          Header
        </header>

        {children}

        <footer style={{ backgroundColor: "ghostWhite", padding: "1rem" }}>
          Footer
        </footer>
      </body>
    </html>
  );
}
